### ISSUE TITLE
Imaging Datasets

### ISSUE THREAD

**Issue by nataliebell333** [pippipalma/MAMBA#1]
Hello, 

Are you able to use this toolbox for nifti files or only mat files? 

Also is there a built in visualization tool?

**Comment by pippipalma** [comment]
Hello,

> Are you able to use this toolbox for nifti files or only mat files?

The toolbox only accepts MAT files that adhere to the specifications outlined in the [User Manual](../blob/main/Docs/UserManual.pdf). Users with datasets in Nifti format can create MAT files after importing the Nifti files using Matlab built-in functions <a href="https://mathworks.com/help/images/ref/niftiread.html" target="_blank">``niftiread``</a> and <a href="https://mathworks.com/help/images/ref/niftiinfo.html" target="_blank">``niftiinfo``</a>. 

Similarly, effect size maps and significance maps can be exported to Nifti format using <a href="https://mathworks.com/help/images/ref/niftiwrite.html" target="_blank">``niftiwrite``</a>.

> Also is there a built in visualization tool?

MAMBA is not intended to provide graphical tools for the visualization of the results, due to the existence of the excellent dedicated tools for medical image visualization, which include open-source solutions such as ImageJ, Horos, FreeSurfer, etc.
